#!/usr/bin/env python3
"""
update-plugin-readmes.py

Insert or replace the cross-platform install block in each plugin's README.md
using marker comments. Idempotent: running twice produces no diff.

Markers:
    <!-- BEGIN cross-platform-install -->
    ...generated content...
    <!-- END cross-platform-install -->

Behavior:
- If the markers exist: replace the content between them.
- If they don't exist: insert the block immediately after the existing
  `## Installation` (or `## Install`) section. If no such section exists,
  append the block at the end of the README.

Subagent-heavy plugins receive an additional `### Behavioral notes on
Gemini and Codex` subsection inside the cross-platform install block.

Exit codes:
  0  All READMEs processed successfully (any mix of replaced/inserted/appended/no-change).
  1  At least one plugin had no README.md.
  2  At least one README has a corrupt marker (BEGIN without END).

Stdlib-only. Python 3.8+.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Optional, Tuple

REPO_ROOT = Path(__file__).resolve().parent.parent
PLUGINS_DIR = REPO_ROOT / "plugins"
MARKETPLACE = REPO_ROOT / ".claude-plugin" / "marketplace.json"

BEGIN_MARKER = "<!-- BEGIN cross-platform-install -->"
END_MARKER = "<!-- END cross-platform-install -->"

# Plugins whose generated commands inline a subagent prompt with a banner
# (see FR-009 in spec.md). On Gemini/Codex these commands run inline rather
# than dispatching a subagent, so READMEs flag the behavioral degradation.
SUBAGENT_HEAVY_PLUGINS = {"core", "spring-boot"}


def render_block(plugin: str) -> str:
    """Render the cross-platform install block for a single plugin."""

    lines = [
        BEGIN_MARKER,
        "<!-- Generated by scripts/update-plugin-readmes.py — do not edit by hand. -->",
        "",
        "## Install on Gemini CLI",
        "",
        "Install the Gemini extension shim (regenerated from the canonical Claude plugin):",
        "",
        "```bash",
        f"# From the repo root",
        f"gemini extensions install ./.gemini-extensions/{plugin}",
        "```",
        "",
        f"On first session, the `using-arkhe-skills` bootstrap skill loads automatically and"
        f" maps Claude-only primitives (`AskUserQuestion`, `TaskCreate`, `EnterPlanMode`,"
        f" the `Skill` tool, the `Agent` tool with `subagent_type`) to Gemini equivalents."
        f" Install the `core` extension first if you have not already — its bootstrap is"
        f" referenced by every other plugin's `GEMINI.md`.",
        "",
        "## Install on Codex CLI",
        "",
        "Codex consumes per-plugin `AGENTS.md` files plus a symlinked skills tree:",
        "",
        "```bash",
        "# Enable experimental skill support (Codex CLI ≥ Dec 2025)",
        "codex --enable skills",
        "",
        f"# From the repo root, wire this plugin into Codex",
        f"mkdir -p ~/.codex/plugins/{plugin}",
        f"cp .codex-marketplace/{plugin}/AGENTS.md ~/.codex/plugins/{plugin}/AGENTS.md",
        f"ln -s \"$(pwd)/plugins/{plugin}/skills\" ~/.codex/plugins/{plugin}/skills",
        "```",
        "",
        f"Codex surfaces commands as trigger phrases inside `AGENTS.md` (it has no native"
        f" slash-command support). The `using-arkhe-skills` bootstrap pointer at the top of"
        f" `AGENTS.md` is loaded on first turn.",
    ]

    if plugin in SUBAGENT_HEAVY_PLUGINS:
        lines.extend(
            [
                "",
                "### Behavioral notes on Gemini and Codex",
                "",
                f"Some commands in `{plugin}` dispatch Claude subagents (a Claude-only"
                f" capability). On Gemini and Codex, those commands ship with the agent's"
                f" prompt **inlined** and a banner:",
                "",
                "> *On Gemini/Codex, the agent that would be invoked on Claude has been"
                " collapsed into this prompt. Behavior is degraded — no parallel"
                " sub-execution.*",
                "",
                "Affected commands degrade gracefully for single-pass workflows (deep"
                " research, code review, debugging) but lose parallel sub-execution and"
                " persistent agent state. Use Claude Code if your workflow requires"
                " multi-agent orchestration.",
            ]
        )

    lines.append(END_MARKER)
    # Trailing blank line keeps the next H2 heading idiomatically separated
    # in the rendered Markdown. find_marker_block() consumes trailing newlines
    # greedily so re-runs don't accumulate blanks.
    return "\n".join(lines) + "\n\n"


def find_marker_block(content: str) -> Optional[Tuple[int, int]]:
    """Return (start, end) char offsets of the marker block, or None."""

    begin_idx = content.find(BEGIN_MARKER)
    if begin_idx == -1:
        return None
    end_idx = content.find(END_MARKER, begin_idx)
    if end_idx == -1:
        # Begin without end is a corrupt state — surface it.
        raise ValueError(
            f"found {BEGIN_MARKER} without matching {END_MARKER}"
        )
    end_idx += len(END_MARKER)
    # Greedily consume all trailing newlines so re-runs (which write a block
    # ending in `\n\n`) don't accumulate blank lines on each run.
    while end_idx < len(content) and content[end_idx] == "\n":
        end_idx += 1
    return begin_idx, end_idx


def find_install_section_end(content: str) -> Optional[int]:
    """Return char offset where the `## Installation` (or `## Install`) section
    ends, so we can insert the new block immediately after it. Returns None
    if no such section exists.
    """

    # Match `## Install` or `## Installation` (case-insensitive at start of line).
    match = re.search(
        r"^##\s+Install(?:ation)?\b.*?$",
        content,
        flags=re.MULTILINE | re.IGNORECASE,
    )
    if not match:
        return None

    # Find the next H2 heading after this one. The install section ends just
    # before that heading; if no next heading, the section ends at EOF.
    after = content[match.end():]
    next_h2 = re.search(r"^##\s+\S", after, flags=re.MULTILINE)
    if next_h2:
        return match.end() + next_h2.start()
    return len(content)


def update_readme(plugin: str, readme_path: Path) -> Tuple[bool, str]:
    """Update a single plugin README. Returns (changed, action).

    `action` is one of: "replaced", "inserted-after-install", "appended",
    "no-change".
    """

    original = readme_path.read_text()
    block = render_block(plugin)

    existing = find_marker_block(original)
    if existing is not None:
        start, end = existing
        new_content = original[:start] + block + original[end:]
        action = "replaced"
    else:
        anchor = find_install_section_end(original)
        if anchor is not None:
            # Insert block after the install section, with a blank line
            # separator if the surrounding text isn't already blank.
            prefix = original[:anchor]
            suffix = original[anchor:]
            sep = "" if prefix.endswith("\n\n") else ("\n" if prefix.endswith("\n") else "\n\n")
            new_content = prefix + sep + block + suffix
            action = "inserted-after-install"
        else:
            # No install section — append at the end.
            sep = "\n\n" if not original.endswith("\n\n") else ""
            new_content = original.rstrip() + "\n\n" + block
            action = "appended"

    if new_content == original:
        return (False, "no-change")

    readme_path.write_text(new_content)
    return (True, action)


def list_plugins() -> list:
    """Return the list of plugin names from marketplace.json."""

    if not MARKETPLACE.exists():
        # Fallback: scan plugins/ directory.
        return sorted(p.name for p in PLUGINS_DIR.iterdir() if p.is_dir())

    data = json.loads(MARKETPLACE.read_text())
    return [entry["name"] for entry in data.get("plugins", [])]


def main(argv: list) -> int:
    plugins = list_plugins()
    if not plugins:
        print("error: no plugins found", file=sys.stderr)
        return 1

    print(f"update-plugin-readmes: processing {len(plugins)} plugins")
    print()

    summary = {"replaced": 0, "inserted-after-install": 0, "appended": 0, "no-change": 0, "missing": 0}

    for plugin in plugins:
        readme = PLUGINS_DIR / plugin / "README.md"
        if not readme.exists():
            print(f"  [{plugin}] MISSING README.md")
            summary["missing"] += 1
            continue

        try:
            changed, action = update_readme(plugin, readme)
        except ValueError as exc:
            print(f"  [{plugin}] ERROR: {exc}", file=sys.stderr)
            return 2

        marker = "*" if changed else " "
        print(f"  {marker} [{plugin}] {action}")
        summary[action] = summary.get(action, 0) + 1

    print()
    print("Summary:")
    for action, count in summary.items():
        if count:
            print(f"  {action}: {count}")

    if summary["missing"]:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
